name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-android:
    runs-on: ubuntu-22.04

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java 17 (required for sdkmanager)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Install Linux dependencies
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip python3-pip \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses-dev libtinfo6 cmake \
            libffi-dev libssl-dev wget

      # Add ~/.local/bin to PATH
      - name: Add local bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Cache pip downloads to speed up dependency installs
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-android-widgets-buildozer-cython-0.29.34
          restore-keys: |
            ${{ runner.os }}-pip-

      # Prepare Buildozer SDK folder
      - name: Prepare Android SDK folder
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk

      # Install Android command line tools
      - name: Install Android cmdline tools
        run: |
          cd ~/.buildozer/android/platform/android-sdk

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-*.zip

          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest || true

          # Buildozer expects old tools/bin/sdkmanager
          mkdir -p tools/bin

          ln -s ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager tools/bin/sdkmanager
          ln -s ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/avdmanager tools/bin/avdmanager

      # Accept Android licenses
      - name: Accept Android licenses
        run: |
          yes | ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses

      # Install Android build-tools required for aidl
      - name: Install Android build-tools
        run: |
          yes | ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;29.0.0"

      # Build APK
      - name: Build APK
        id: build
        run: |
          pip install --upgrade pip
          pip install android-widgets git+https://github.com/kivy/buildozer legacy-cgi setuptools cython==0.29.34
          buildozer android debug
          APK=$(find ./bin -name "*-debug.apk" | head -n 1)
          echo "apk=$APK" >> $GITHUB_OUTPUT
          echo "Built APK: $APK"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.build.outputs.apk }}
